### PR TITLE
Alarm addition

### PR DESCRIPTION
**Pull request by ravencode69**
Added alarm function

### CODE REVIEW

**Comment by ravencode69** [comment]
hey can you please delete .repl file, poetry, pyprojrct.toml before merging because i wasn't able to find how to not incorporate those files.

**Comment by karunakaran186** [comment]
After reviewing i shall merge it out :) @ravencode69 Cool didi

**Review by karunakaran186 — COMMENTED** [review]
Review under progress!!! wait for a day didi @ravencode69

**Comment by ravencode69** [comment]
sure @karunakaran186

**Pull request merged**
