### PR TITLE
#issue58solved

### PR DESCRIPTION
**Pull request by anipaul2**
Added wolframalpha, StackOverflow, and restart options

### CODE REVIEW

**Comment by anipaul2** [comment]
@karunakaran186 please see now and tell if there is something wrong.

**Comment by anipaul2** [comment]
@karunakaran186 please review it

**Review by karunakaran186 — APPROVED** [review]
Wow!!! :)

**Comment by karunakaran186** [comment]
Conflicts found resolve it :(

**Comment by karunakaran186** [comment]
conflicts found pls resolve it and make an fresh PR :)

**Pull request closed without merging**
