### PR TITLE
added screen recorder functionality

### PR DESCRIPTION
**Pull request by Phoenix-031**
Added screen record function and resolved the issues. :)
PR for feature addition #23 .

### CODE REVIEW

**Review by karunakaran186 — APPROVED** [review]
wonderful feature!!!! :) @Phoenix-031

**Comment by karunakaran186** [comment]
Screenshot 2022-03-08 231451
i couldn't able to view the recorded file bro :( @Phoenix-031

**Comment by Phoenix-031** [comment]
@karunakaran186  okay so is the code giving an error message or is the video file not playable?

**Comment by karunakaran186** [comment]
yup pls make a correction of it :)

**Comment by Phoenix-031** [comment]
@karunakaran186 i have updated the function according to the updated code base do look into it and tell me if the problem is still persisting

**Comment by karunakaran186** [comment]
conflicts found!!!!

**Pull request closed without merging**
