### PR TITLE
Gssoc 2022 

### PR DESCRIPTION
**Pull request by karunakaran186**
Raise an issue and Make an PR

### CODE REVIEW

**Comment by AnonymousCodes911** [comment]
Hey! @karunakaran186  
It would be nice if you can raise some issues so that we can contribute to them.

**Comment by karunakaran186** [comment]
Yeah ok sure...

ping me in whatsapp
8754659759

**Comment by Krishna841** [comment]
Heyy There's no option to raise an issue in here. What to do?

**Comment by Krishna841** [comment]
THere's no option to raise an issue in this repo, Should we head over the the codecrusher repo to raise the issue and work on it?

**Comment by karunakaran186** [comment]
Yes, you can do that. Bro

**Comment by Krishna841** [comment]
I can't raise the issue because the owner has restricted that feature only to past contributors to the project. :| Can you change the permissions?

**Comment by karunakaran186** [comment]
Yes, I can.

Cool

Pls ping me on this num
8754659759

**Pull request closed without merging**
