### PR TITLE
Added Volume control and battery status feature

### PR DESCRIPTION
**Pull request by shrey2003**
#Issue52 - Made updation in main.py and modules.py for adding volume control and battery status feature

### CODE REVIEW

**Comment by shrey2003** [comment]
Issue #52

**Comment by karunakaran186** [comment]
Review under progress!!!

**Comment by karunakaran186** [comment]
conflicts found !!!
@shrey2003

**Review by karunakaran186 — APPROVED** [review]
Really an unique feature @shrey2003  🔢

**Review by karunakaran186 — APPROVED** [review]

**Comment by shrey2003** [comment]
Thanks @karunakaran186 looking forward for contributing more on this project

**Pull request merged**
