### PR TITLE
Updated code

### PR DESCRIPTION
**Pull request by ghost**
Added feature so that KAVI can capture images from Camera and shutdown or logoff the machine.

### CODE REVIEW

**Comment by karunakaran186** [comment]
> Added feature so that KAVI can capture images from Camera and shutdown or logoff the machine.

yeah you can make an PR and connect with me we shall discuss

**Comment by saiadityaviswanadham** [comment]
@karunakaran186  I just received a mail saying that I have been assigned to this PR. So since I already raised the PR, I have nothing to do now right? Merging will be done from your side right? Just want to clarify this...

**Comment by karunakaran186** [comment]
Cool let ill review it

**Comment by karunakaran186** [comment]
conflicts found Resolve it ASAP !!!

**Comment by karunakaran186** [comment]
conflicts found Resolve it ASAP !!!

**Comment by saiadityaviswanadham** [comment]
@karunakaran186 How should I resolve conflict. I have added my feature code in code file. I have edited only code file. But it is showing Conflicts.Can you help me out

**Pull request closed without merging**
