### PR TITLE
added flip a coin and pick a random number feature

### LINKED ISSUE #65: updating requirements.txt
ss1
ss2
ss3

The above modules are absent in the requirements.txt file which are essential for program to run

Please assign me under GSSOC'22 to update the file @karunakaran186

### PR DESCRIPTION
**Pull request by jeevanalok**
Fixes #65  #42 

Added flip a coin to tell the user if it's head or tails for those times we can't decide on something and additionally added pick a random number feature.
And also updated requirements.txt as per new code base.

This PR is made under **GSSOC'22**

Here's a sample screenshot
ss

### CODE REVIEW

**Comment by jeevanalok** [comment]
@karunakaran186 please review it

**Review by karunakaran186 — CHANGES_REQUESTED** [review]
Check the old code you have removed PIL lib !!! without removing change the code!!!! ping me @8754659759 immediately :) pls ----)

**Comment by jeevanalok** [comment]
@karunakaran186 have fixed two issues under one pr. please review

**Comment by karunakaran186** [comment]
conflicts found pls resolve it ASAP!!! :)

**Comment by karunakaran186** [comment]
i shall closing this PR :) Make a fresh PR after resolving all the conflicts

**Pull request closed without merging**
