### PR TITLE
changed the entire structure

### PR DESCRIPTION
**Pull request by Praj-17**
Hello there, 
I have changed the entire code structure, As I mentioned in mu issue #94. The major changes that I have made are

1. Removed the irritating, space-consuming dialogues and created a simple JSON file instead.
2. Well-managed the code, Created proper functions in separate files, and named them accordingly. 
3. Added the print and speak so that we need not type it again and again.
4. Implemented a Deep Learning Sequential model. That could easily understand and manipulate user input.
5. Implemented Natural Language Processing for Text Preprocessing and betterment of the Deep learning model.
6. Added a dozen of new features that you may see in the features folders.
7. We are also saving Data in the data.csv folder so that it is easier to debug and manipulate.
8. Also, Added the _wake-up_ word as '_kavi'_ that will make it even interesting.
9. Added a def inactive() that will make it inactive after a certain time.
10. Plus there is a lot more that you may discover on your own.
11. renamed the code.py file to the initial_code.py file since code is a reserved keyword.

Now, there are some more points that I would Like to elaborate on.
1. Please change all the API ids as soon as you get the code. There are 2 API ids used. Wolfram API and Serp API. Please change them as soon as you get them.
2. Whenever you change the database(_intents.json_) file, you need to re-train the model by running the Train_model file.
3. Then you need to run the main file again.
4. There might be an error with the voice assistant that I have Used.  If you do not have that Voice. Kindly install it or simply change the voice number in the _speak.py_ file.

Here is a demo video that I have Added to show its live demo.
[Demo Video](https://drive.google.com/file/d/1jPDQQ0EXRaCUHLS9CigLRKFaXS-wWBDy/view?usp=sharing)

Feel free to contact me under any other issue on my following handles.
THE LINK HUB

Email 
1 - pwaykos1@gmail.com
2- prajwal.22010591@viit.ac.in

Resume
https://drive.google.com/file/d/1XG5AX_hk46MBHciLqpEn3w2j_HqlpOev/view?usp=sharing

LinkedIn
https://www.linkedin.com/in/prajwal-waykos-a78105207/

My Website 
http://prajtech.xyz/

Twitter
https://twitter.com/waykos_prajwal

Git Hub
https://github.com/Praj-17

Drive Sharable
https://drive.google.com/drive/u/2/folders/1WTgYq3rXPaE8_qHWLkPcmdkUkz_-ghWP

Tableau 
https://public.tableau.com/app/profile/prajwal.waykos

Hacker Rank
https://www.hackerrank.com/prajwal_22010591

Phone - 
1.- +917249542810
2. - +919405398736

Facebook
https://www.facebook.com/prajwal.waykos

Instagram
https://www.instagram.com/the_resurrection17/

@karunakaran186 Waiting for immediate response.

### CODE REVIEW

**Comment by karunakaran186** [comment]
Awesome work Sir contact me via discord karan007#5909

**Comment by Praj-17** [comment]
I have sent you a request. I hope you have received it.  Also, I hope You will merge this code to the main file.

**Comment by karunakaran186** [comment]
Awesome work sir! 💯

**Comment by Praj-17** [comment]
What should I do next, When can I expect the merge?

**Comment by Praj-17** [comment]
When Can I Expect the merge, What should I do next?

**Pull request closed without merging**
