### PR TITLE
Improve code structure

### PR DESCRIPTION
**Pull request by adii21-Ux**
Arranged some code which was just lying outside function and was disturbing the normal flow of program

### CODE REVIEW

**Comment by adii21-Ux** [comment]
@karunakaran186 review please

**Comment by karunakaran186** [comment]
yeah sure!!!

**Review by karunakaran186 — CHANGES_REQUESTED** [review]
Do kindly have a look at Main.py in repository because modularity was done in code do kindly make contribution according to that code base :)

**Comment by karunakaran186** [comment]
conflicts found kindly make an fresh PR

**Pull request closed without merging**
